name: 'github actions publish x-cmd/dev'

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 11 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: install x-cmd && setup ssh publish
        run:  |
              eval "$(curl https://get.x-cmd.com/dev)" || true
              git clone git@gitee.com:x-cmd/x-cmd.git && cd x-cmd || exit
              x gh-action ssh "$SSH_PRIVATE_KEY" agent-zero 0@x-cmd.com || true
              xws pub || true
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
